In [1]:
#Import necessary modules and libraries
import numpy as np
import random

In [2]:
#Exercise 4.1
#Problem 1
#1)
empty_array = np.empty((2,2))
print(empty_array)

[[0.00000000e+000 1.07552139e-311]
 [1.07552139e-311 1.07552139e-311]]


In [3]:
#2)
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
#3)
ones_array.fill(4)
print(ones_array)

[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


In [5]:
#4)
zeros_like = np.zeros_like(ones_array)
zeros_like

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
#5)
a = np.arange(1,10)
b = a.reshape(3,3)
print(b)
ones_like = np.ones_like(b)
print(ones_like)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
#6)
new_list = [1,2,3,4]
print(new_list)
new_array = np.array(new_list)
new_array

[1, 2, 3, 4]


array([1, 2, 3, 4])

In [8]:
#Problem 2
#1)
array_range = np.arange(10, 49)
array_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [9]:
#2)
array_linspace = np.linspace(0,8, endpoint = True, num = 9)
array_linspace.reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [10]:
#3)
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#4)
random_array = np.random.randint(0,30, size = 30)
random_array
array_mean = np.mean(random_array)
array_mean

np.float64(15.766666666666667)

In [12]:
#5)
random_array_1 = np.random.randint(0, 50, size = (10,10))
random_array_1
print("The maximum value is: ", np.max(random_array_1))
print("The minimum value is: ", np.min(random_array_1))

The maximum value is:  49
The minimum value is:  0


In [13]:
#6)
zero_array = np.zeros(5)
zero_array
zero_array[4] = 1
zero_array

array([0., 0., 0., 0., 1.])

In [14]:
#7
arr = [1,2,0,0,4,0]
arr1 = np.array(arr)
reversed = np.flip(arr1)
reversed

array([0, 4, 0, 0, 2, 1])

In [15]:
#8)
two_d_array = np.array([[2,3,4], [2,3,4]])
two_d_array[0:2, 0:3:2] = 1
two_d_array[0:2, 1:3:2] = 0
two_d_array

array([[1, 0, 1],
       [1, 0, 1]])

In [16]:
#9)
eight_d_array = np.zeros((8,8))

eight_d_array[::2, ::2] = 1
eight_d_array[1::2, 1::2] = 1
eight_d_array


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [17]:
#Problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);
#1)
print(x+y, v+w)

[[ 6  8]
 [10 13]] [20 22]


In [18]:
#2)
print(x-y, v-w)

[[-4 -4]
 [-4 -3]] [-2 -2]


In [19]:
#3)
print(x*3, v*4)

[[ 3  6]
 [ 9 15]] [36 40]


In [20]:
#4)
print(x ** 2, v ** 2)

[[ 1  4]
 [ 9 25]] [ 81 100]


In [21]:
#5)
print("The dot product of x and y is: ",np.dot(x,y), sep = '\n\n')
print("The dot product of x and v is: ",np.dot(x,v), sep = '\n\n')
print("The dot product of v and w is: ",np.dot(v,w), sep = '\n\n')

The dot product of x and y is: 

[[19 22]
 [50 58]]
The dot product of x and v is: 

[29 77]
The dot product of v and w is: 

219


In [22]:
#6)
#Concatenation of matrices
print("The concatenation along row axis: ", np.concatenate((x,y), axis = 0))
print("The concatenation along column axis: ",np.concatenate((x,y), axis = 1))

The concatenation along row axis:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
The concatenation along column axis:  [[1 2 5 6]
 [3 5 7 8]]


In [23]:
#7)
np.concatenate((x,v), axis = 1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#7)
np.concatenate((x,v), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [24]:
"""
We got error while performing concatenation along row and column as the matrices need to be of same shape in order to perform concatenation.
"""

'\nWe got error while performing concatenation along row and column as the matrices need to be of same shape in order to perform concatenation.\n'

In [30]:
#Problem 4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [32]:
#Problem 4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [33]:
#A.A−1 = I
np.matmul(A, np.linalg.inv(A))

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [34]:
A @ np.linalg.inv(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [35]:
#AB ̸= BA
AB = A @ B
BA = B @ A
AB == BA

array([[False, False],
       [False, False]])

In [36]:
# (AB)T = BTAT
AB_T = np.transpose(AB)
BA_T = np.transpose(B) @ np.transpose(A)
AB_T == BA_T

array([[ True,  True],
       [ True,  True]])

In [44]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
X = np.linalg.solve(A,B)
X

array([ 2.,  1., -2.])

In [45]:
#Using Inverse Method
A_inv = np.linalg.inv(A)
X = A_inv @ B
X

array([ 2.,  1., -2.])

In [ ]:
#4.2 Experiment: How Fast is Numpy?
#random.seed(0)
#Element-wise Addition
from timeit import timeit
A = [random.randint(0, 100) for _ in range(1000000)]
B  = [random.randint(0, 100) for _ in range(1000000)]
Aa = np.array(A)
Bb = np.array(B)
def add_python(X, Y):
    return [x + y for x, y in zip(X, Y)]
def add_numpy(X, Y):
    return np.add(X, Y)

python_time = timeit(lambda: add_python(A, B), number = 1000)
numpy_time = timeit(lambda: add_numpy(Aa, Bb), number = 1000)
print(f"The time taken to python is: {python_time:.6f}")
print(f"The time taken to numpy is: {numpy_time:.6f}")


The time taken to python is: 107.644328
The time taken to numpy is: 7.497885


In [42]:
#Element-wise Multiplication
def multiply_python(X, Y):
    return [x * y for x, y in zip(X, Y)]
def multiply_numpy(X, Y):
    return np.multiply(X, Y)
python_time = timeit(lambda: multiply_python(A, B), number = 1000)
numpy_time = timeit(lambda: multiply_numpy(Aa, Bb), number = 1000)
print(f"The time taken to python is: {python_time:.6f}")
print(f"The time taken to numpy is: {numpy_time:.6f}")

The time taken to python is: 155.638937
The time taken to numpy is: 5.202322


In [54]:
#Dot Product
A = [random.randint(0, 100) for _ in range(1000000)]
B  = [random.randint(0, 100) for _ in range(1000000)]
Aa = np.array(A)
Bb = np.array(B)

def dot_python(X, Y):
    return sum(x * y for x, y in zip(X, Y))
def dot_numpy(X, Y):
    return np.dot(X, Y)
python_time = timeit(lambda: dot_python(A, B), number = 1000)
numpy_time = timeit(lambda: dot_numpy(Aa, Bb), number = 1000)


In [55]:
print(f"The time taken to python during dot product is: {python_time:.6f}")
print(f"The time taken to during dot product numpy is: {numpy_time:.6f}")

The time taken to python during dot product is: 131.858141
The time taken to during dot product numpy is: 1.049829


In [ ]:
#Matrix Multiplication
#Decreased the size of matrices from 1000* 1000 to 100*100 due extreme delay in processing 
def matrix_multiply_python(X, Y):
    result = [[0 for _ in range(len(Y[0]))] for _ in range(len(X))]
    for i in range(len(X)):
        for j in range(len(Y[0])):
            for k in range(len(Y)):
                result[i][j] += X[i][k] * Y[k][j]
    return result

#Matrix Multiplication using Numpy
def matrix_multiply_numpy(X, Y):
    return np.matmul(X, Y)

#Matrix generation of size 1000 * 1000

def generate_matrix(rows, cols):
    return [[random.randint(0, 100) for _ in range(cols)] for _ in range(rows)]

# Generate test matrices
A = generate_matrix(100, 100)  # 100x100 matrix
B = generate_matrix(100, 100)  # 100x100 matrix

# Convert to NumPy arrays
Aa = np.array(A)
Bb = np.array(B)
python_time = timeit(lambda: matrix_multiply_python(A, B), number = 1000)
numpy_time = timeit(lambda: matrix_multiply_numpy(Aa, Bb), number = 1000)



In [50]:
print(f"The time taken to python during matrix multiplication is: {python_time:.6f}")
print(f"The time taken to during matrix multiplication numpy is: {numpy_time:.6f}")

The time taken to python during matrix multiplication is: 183.842236
The time taken to during matrix multiplication numpy is: 2.115379
